
version: '2.4'
services:
  server:
    build: 
      context: ./server
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
  client:
    build: 
      context: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
